---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: blog-virtual-service
  namespace: istio-system
spec:
  gateways:
    - platform/default-gateway
  hosts:
  - blog.k8s.kieranbamforth.me
  http:
  - name: "blog-gatsby"
    match:
      - uri:
          exact: /
    route:
    - destination:
        host: blog-service-gatsby.apps.svc.cluster.local
        port:
          number: 80
  - name: "blog-gatsby-static"
    match:
      - uri:
          regex: "/(static/|page-data|webpack-|app-|framework-|component-).*"
    route:
    - destination:
        host: blog-service-gatsby.apps.svc.cluster.local
        port:
          number: 80
  - name: "blog"
    route:
    - destination:
        host: blog-service.apps.svc.cluster.local
        port:
          number: 80
