apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: blog-vservice
  namespace: istio-system
spec:
  gateways:
    - default-gateway
  hosts:
  - blog.k8s.istio.kieranbamforth.me
  - www.kieranbamforth.me
  http:
  - name: "blog-gatsby"
    match:
      - uri:
          exact: /
    route:
    - destination:
        host: blog-service-gatsby.blog.svc.cluster.local
        port:
          number: 80
  - name: "blog"
    route:
    - destination:
        host: blog-service.blog.svc.cluster.local
        port:
          number: 80
