name: lol

on:
  push:
    branches: [runner]

jobs:
  kubernetes:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Kubectl
        uses: azure/setup-kubectl@v1
        id: install

      - name: Kubernetes Context...
        uses: azure/k8s-set-context@v1
        id: setcontext
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Deploy Blog
        uses: Azure/k8s-deploy@v1.4
        with:
          namespace: blog
          manifests: |
              kubernetes/knative.yml
          images: 'kieranbamforth/blog:1'
